
import AppHeader from "@/components/app-header";
import { routing } from "@/messages/routing";
import type { Metadata } from "next";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { Open_Sans } from "next/font/google";
import { notFound } from "next/navigation";
import "../globals.css";

const openSans = Open_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}

export default async function RootLayout({ children, params }: RootLayoutProps) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  const messages = await getMessages()

  return (
    <html lang={locale} dir={locale === "he" ? "rtl" : "ltr"}>
      <body
        className={`${openSans.className} antialiased flex items-center justify-center`}
      >
        <section className="grid grid-4 max-w-7xl w-full py-4">
          <NextIntlClientProvider messages={messages}>
            <AppHeader />
            <main className="p-4">
              {children}
            </main>
          </NextIntlClientProvider>
        </section>
      </body>
    </html>
  );
}
